version: '3.8'

services:
  postgres:
    image: docker.io/library/postgres:13
    environment:
      POSTGRES_USER: parallama
      POSTGRES_PASSWORD: development
      POSTGRES_DB: parallama
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: docker.io/library/redis:5
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
