# Parallama Configuration

# Server settings
server:
  host: "127.0.0.1"
  port: 8000
  workers: 4
  reload: false
  log_level: "info"

# Database settings
database:
  url: "postgresql://parallama:${DB_PASSWORD}@localhost/parallama"
  pool_size: 5
  max_overflow: 10
  pool_timeout: 30

# Redis settings
redis:
  url: "redis://localhost:6379/0"
  pool_size: 10

# Authentication
auth:
  jwt_secret_file: "/etc/parallama/jwt_secret"
  token_expiry: 3600  # 1 hour
  refresh_token_expiry: 2592000  # 30 days

# Rate limiting
rate_limit:
  default_requests: 1000
  default_window: 3600  # 1 hour
  redis_prefix: "ratelimit:"

# Gateway settings
gateway:
  ollama:
    url: "http://localhost:11434"
    timeout: 300
    max_tokens: 4096
  
  # Model mappings for OpenAI compatibility
  model_map:
    "gpt-3.5-turbo": "llama2"
    "gpt-4": "llama2:70b"

# Logging
logging:
  file: "/var/log/parallama/service.log"
  level: "info"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  max_size: 10485760  # 10MB
  backup_count: 5

# Usage tracking
usage:
  enabled: true
  storage_days: 30
  redis_prefix: "usage:"
